require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Rails/InverseOf:
  Enabled: false
Rails/LexicallyScopedActionFilter:
  Enabled: false
Style/GuardClause:
  Enabled: false

AllCops:
  # DisabledByDefault: true
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'public/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'features/**/*'
    - 'bin/**/*'
    - 'test/factories.rb'

Rails/FilePath:
  Exclude:
    - 'config/application.rb'

Rails/SkipsModelValidations:
  Exclude:
    - 'app/packs/core/folders/models/folder.rb'
    - 'app/packs/secondaries/secondary_sales/jobs/fund_raise_allocation_job.rb'
    - 'app/packs/secondaries/secondary_sales/jobs/allocation_job.rb'
    - 'app/packs/secondaries/secondary_sales/jobs/allocation_base.rb'
    - 'app/packs/startups/investments/jobs/investment_percentage_holding_job.rb'
    - 'app/packs/startups/investments/services/interactors/create_audit_trail.rb'
    - 'app/packs/core/entities/models/entity.rb'
    - 'app/jobs/offer_spa_job.rb'
    - 'app/packs/funds/investment_opportunities/jobs/investment_opportunity_job.rb'
    - 'app/packs/funds/capital_commitments/models/capital_commitment.rb'
    - 'app/packs/secondaries/secondary_sales/jobs/custom_allocation_job.rb'
    - 'app/packs/secondaries/secondary_sales/jobs/custom_allocation_job2.rb'
Rails/HasAndBelongsToMany:
  Exclude:
    - 'app/models/role.rb'
Naming/MethodName:
  Exclude:
    - 'app/packs/startups/investments/models/investment.rb'
    - 'app/packs/core/investors/models/investor.rb'
Naming/AccessorMethodName:
  Exclude:
    - 'app/datatables/note_datatable.rb'

Lint/DuplicateBranch:
  Exclude:
    - 'app/packs/startups/investments/helpers/investments_helper.rb'
Lint/MissingSuper:
  Exclude:
    - 'app/services/*'

Rails/OutputSafety:
  Exclude:
    - 'config/initializers/client_side_validations.rb'
Style/OptionalBooleanParameter:
  Exclude:
    - 'app/packs/startups/investments/helpers/investments_helper.rb'
    - 'app/packs/core/base/mailers/email_currency_helper.rb'

Security/Eval:
  Exclude:
    - 'app/packs/secondaries/secondary_sales/jobs/custom_allocation_job2.rb'
    - 'app/packs/secondaries/secondary_sales/jobs/custom_allocation_job.rb'
    - 'app/packs/secondaries/offers/models/offer.rb'
    - 'app/packs/secondaries/interests/models/interest.rb'
# Metrics Cops
Metrics/CyclomaticComplexity:
  Max: 10
  Enabled: true
  Exclude:
    - 'app/packs/core/users/models/user.rb'
Metrics/PerceivedComplexity:
  Max: 12
  Exclude:
    - 'app/packs/core/users/models/user.rb'
    - 'app/packs/core/tasks/controllers/tasks_controller.rb'
    - 'app/packs/core/uploaders/file_uploader.rb'
Metrics/ClassLength:
  Description: 'Avoid classes longer than 100 lines of code.'
  Max: 200
  Enabled: true

Metrics/ModuleLength:
  Description: 'Avoid modules longer than 100 lines of code.'
  Max: 100
  Enabled: true

Metrics/ParameterLists:
  Description: 'Pass no more than four parameters into a method.'
  Max: 4
  Enabled: true

Metrics/MethodLength:
  Description: 'Avoid methods longer than 5 lines of code.'
  StyleGuide: '<https://github.com/bbatsov/ruby-style-guide#short-methods>'
  Max: 30
  Enabled: true
  Exclude:
    - 'app/packs/core/users/models/user.rb'
  
Metrics/BlockLength:
  CountComments: false
  Max: 15
  Exclude:
    - 'app/packs/secondaries/secondary_sales/views/secondary_sales/download.xlsx.axlsx'
    - 'app/packs/misc/import_uploads/jobs/import_upload_job.rb'
    - 'app/packs/startups/investments/jobs/investment_percentage_holding_job.rb'
    - 'app/controllers/concerns/investment_concern.rb'
    - 'app/packs/funds/capital_distributions/jobs/capital_distribution_job.rb'
    - 'app/packs/secondaries/offers/models/offer_spa_generator.rb'
    - 'app/packs/secondaries/secondary_sales/jobs/spa_job.rb'
    - 'app/packs/secondaries/secondary_sales/views/secondary_sales/payments.xlsx.axlsx'
  IgnoredMethods:
    - context
    - describe
    - it
    - shared_examples
    - shared_examples_for
    - namespace
    - draw
    - configure
    - group    
    - included