require: rubocop-rails
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
AllCops:
  NewCops: enable
  Include:
    - 'app/*'
    - 'lib/*'