require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Rails/InverseOf:
  Enabled: false
Rails/LexicallyScopedActionFilter:
  Enabled: false
Style/GuardClause:
  Enabled: false

AllCops:
  # DisabledByDefault: true
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'features/**/*'
    - 'bin/**/*'
    - 'test/factories.rb'

Rails/SkipsModelValidations:
  Exclude:
    - 'app/models/folder.rb'
Rails/HasAndBelongsToMany:
  Exclude:
    - 'app/models/role.rb'
Naming/MethodName:
  Exclude:
    - 'app/models/investment.rb'
    - 'app/models/investor.rb'

# Metrics Cops

Metrics/ClassLength:
  Description: 'Avoid classes longer than 100 lines of code.'
  Max: 150
  Enabled: true

Metrics/ModuleLength:
  Description: 'Avoid modules longer than 100 lines of code.'
  Max: 100
  Enabled: true

Metrics/ParameterLists:
  Description: 'Pass no more than four parameters into a method.'
  Max: 4
  Enabled: true

Metrics/MethodLength:
  Description: 'Avoid methods longer than 5 lines of code.'
  StyleGuide: '<https://github.com/bbatsov/ruby-style-guide#short-methods>'
  Max: 25
  Enabled: true

Metrics/BlockLength:
  CountComments: false
  Max: 15
  IgnoredMethods:
    - context
    - describe
    - it
    - shared_examples
    - shared_examples_for
    - namespace
    - draw
    - configure
    - group    