# config/chewy.yml
# separate environment configs
test:
  host: 'localhost:9200'
  prefix: 'test'
staging:
  host: '3.111.119.22:9200'
  prefix: 'staging'
production:
  host: '3.111.119.22:9200'
  prefix: 'production'
development:
  host: 'localhost:9200'