# config/chewy.yml
# separate environment configs
test:
  host: 'localhost:9200'
  prefix: 'test'
staging:
  host: '<%= ENV["ELASTIC_SEARCH_URL"] %>'
  prefix: 'staging'
sandbox:
  host: '<%= ENV["ELASTIC_SEARCH_URL"] %>'
  prefix: 'staging'
production:
  host: '<%= ENV["ELASTIC_SEARCH_URL"] %>'
  prefix: 'production'
development:
  host: 'localhost:9200'