# config/chewy.yml
# separate environment configs
test:
  host: '<%= ENV["ELASTIC_SEARCH_URL"] %>'
  prefix: 'test<%= ENV["TEST_ENV_NUMBER"] %>'
staging:
  host: '<%= ENV["ELASTIC_SEARCH_URL"] %>'
  prefix: 'staging'
production:
  host: '<%= ENV["ELASTIC_SEARCH_URL"] %>'
  prefix: 'production'
development:
  host: 'localhost:9200'