individual_kyc:
  - details: "Collect PAN card"
    due_in_days: 0
    action_link: "https://example.com/upload-pan"
    help_link: "https://example.com/help-pan"
  - details: "Verify address proof"
    due_in_days: 2
    action_link: "https://example.com/upload-address-proof"
    help_link: "https://example.com/help-address-proof"
  - details: "Schedule in-person verification"
    due_in_days: 5
    action_link: "https://example.com/schedule-verification"
    help_link: "https://example.com/help-verification"

capital_commitment:
  - details: "Prepare commitment agreement"
    due_in_days: 1
    action_link: "https://example.com/prepare-agreement"
    help_link: "https://example.com/help-agreement"
  - details: "Send agreement for signature"
    due_in_days: 3
    action_link: "https://example.com/send-agreement"
    help_link: "https://example.com/help-send-agreement"
