# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
# Place this file at config/sidekiq.yml and Sidekiq will
# pick it up automatically.
---
:verbose: false
:concurrency: 10
:timeout: 25

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
:queues:
  - [critical, 3]
  - [serial, 1]
  - [doc_gen, 1]
  - [default, 2]
  - [low, 1]
  - [chewy, 1]

:limits:
  serial: 1 # We need this in order to avod mysql dealdlocks, specially in import of large data sets. When imports happen, ex for commitments, then the commitments update the funds, but if this happens in multiple sidekiq jobs then they deadlock on the fund update.
  doc_gen: 1 # We need this as the document generator we use libreoffice, sometimes returns false and does not generate the docs if used in parallel


# you can override concurrency based on environment
production:
  :concurrency: 25
staging:
  :concurrency: 15