default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 100

  workers:
    - queues: "*"
      threads: 5
      processes: 1
      polling_interval: 0.1
    - queues: [ serial, doc_gen ]
      threads: 1
      polling_interval: 0.1
      processes: 1

development:
  <<: *default  

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
  dispatchers:
    - recurring_tasks:
        replication_health_job:
          class: ReplicationHealthJob
          args: [ ]
          schedule: every 5 minute
  
