default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 100
  workers:
    - queues: "*"
      threads: 5
      processes: 1
    - queues: [ serial ]
      threads: 1
      processes: 1
    - queues: [ doc_gen ]
      threads: 1
      processes: 1

development:
  <<: *default    

test:
  <<: *default

staging:
  <<: *default
  # dispatchers:
  #   - recurring_tasks:
  #       replication_health_job:
  #         class: ReplicationHealthJob
  #         args: [ ]
  #         schedule: every 5 minutes

production:
  <<: *default
  
  
