metadata:
      stewards:
      - "@CapHive/core"
      slack_channels:
      - "#core"
      enforce_privacy: true  # will make everything private that is not in
      dependencies:
        - app/packs/core