# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  install-cache:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

  test:
    runs-on: ubuntu-latest
    services:
      # How to use MySQL
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
        - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      # How to use Redis
      redis:
        image: redis
        ports:
        - 6379:6379
      # How to use Elasticsearch
      elasticsearch:
        image: elasticsearch:7.11.1
        ports:
        - 9200:9200
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get install -y mysql-client libmysqlclient-dev libreoffice    

      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      
      - name: Run tests
        env:
          CI: true
          RAILS_ENV: test
          
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          
        run: |
          bundle
          bin/rails db:create
          bin/rails db:schema:load
          bundle exec bin/rails runner -e test ElasticImporterJob.new.reset
          bundle exec rake parallel:create
          bundle exec rake parallel:setup
          parallel_cucumber

      - name: "Deploy"
        uses: miloserdow/capistrano-deploy@master
        with:
          target: staging # Defines the environment that will be used for the deployment
          deploy_key: ${{ secrets.DEPLOY_ENC_KEY }} # Name of the variable configured in Settings/Secrets of your github project